# Write your MySQL query statement below
SELECT S.USER_ID,
ROUND(AVG(
    CASE WHEN
    M.ACTION='CONFIRMED' THEN 1
    ELSE 0 END
),2) AS CONFIRMATION_RATE
FROM SIGNUPS S
LEFT JOIN 
CONFIRMATIONS M ON S.USER_ID=M.USER_ID
GROUP BY S.USER_ID 
ORDER BY S.USER_ID 